_wandb:
    value:
        cli_version: 0.24.0
        e:
            8otufhhrfix0mnwt4odwld86sxlon7v8:
                args:
                    - data/train_data.npz
                    - data/val_data.npz
                    - --epochs
                    - "40"
                    - --batch-size
                    - "64"
                    - --lr
                    - "3e-4"
                    - --device
                    - cuda
                    - --run-name
                    - spoter_v1_baseline
                    - --wandb-project
                    - BB3lAowfaCGkIlsby
                    - --wandb-entity
                    - aber-islam-dev-jvai
                codePath: comparison model/BDSLW_SPOTER/train.py
                codePathLocal: comparison model/BDSLW_SPOTER/train.py
                cpu_count: 12
                cpu_count_logical: 24
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "1073038127104"
                        used: "291530354688"
                email: aber.islam.dev@gmail.com
                executable: /home/raco/Repos/bangla-sign-language-recognition/.venv/bin/python3
                git:
                    commit: 14fa1a65289eabc0e8415a49d420aaed637eb30f
                    remote: git@github.com:iamaber/bangla-sign-language-recognition.git
                gpu: NVIDIA GeForce RTX 3090 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10752
                      memoryTotal: "25757220864"
                      name: NVIDIA GeForce RTX 3090 Ti
                      uuid: GPU-91deda27-1cc7-c1f8-f795-49aafdbd368d
                host: raco-ubuntu
                memory:
                    total: "100243935232"
                os: Linux-6.14.0-37-generic-x86_64-with-glibc2.39
                program: /home/raco/Repos/bangla-sign-language-recognition/comparison model/BDSLW_SPOTER/train.py
                python: CPython 3.12.3
                root: /home/raco/Repos/bangla-sign-language-recognition
                startedAt: "2026-01-28T14:41:24.733574Z"
                writerId: 8otufhhrfix0mnwt4odwld86sxlon7v8
        m: []
        python_version: 3.12.3
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 3
                - 13
                - 16
            "4": 3.12.3
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
batch_size:
    value: 64
device:
    value: cuda
epochs:
    value: 40
learning_rate:
    value: 0.0003
model:
    value: SPOTER
num_classes:
    value: 60
